DROP TABLE IF EXISTS submission_testcase_result;
DROP TABLE IF EXISTS submission;
DROP TABLE IF EXISTS submission_overall_status;
DROP TABLE IF EXISTS problem_testcase;
DROP TABLE IF EXISTS solution;
DROP TABLE IF EXISTS homework_problem;
DROP TABLE IF EXISTS homework;
DROP TABLE IF EXISTS discussion_comment;
DROP TABLE IF EXISTS discussion;
DROP TABLE IF EXISTS classes_member;
DROP TABLE IF EXISTS login_log;
DROP TABLE IF EXISTS problem;
DROP TABLE IF EXISTS announcement;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS classes;
DROP TABLE IF EXISTS teacher;
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS judge_status;

CREATE TABLE admin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(100),
  sex VARCHAR(16),
  birth DATE,
  phone VARCHAR(32),
  email VARCHAR(255),
  avatar VARCHAR(512),
  last_login_ip VARCHAR(45),
  last_login_time TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE announcement (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  content CLOB NOT NULL,
  time TIMESTAMP NOT NULL,
  is_pinned BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE teacher (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(100),
  sex VARCHAR(16),
  phone VARCHAR(32),
  email VARCHAR(255),
  avatar VARCHAR(512),
  title VARCHAR(128),
  last_login_time TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  creator_id BIGINT,
  code VARCHAR(64),
  start_date DATE,
  end_date DATE,
  description CLOB,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE student (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(100),
  sex VARCHAR(16),
  birth DATE,
  phone VARCHAR(32),
  email VARCHAR(255),
  avatar VARCHAR(512),
  background VARCHAR(512),
  ac INT,
  submit INT,
  school VARCHAR(255),
  score INT,
  last_login_time TIMESTAMP,
  last_language VARCHAR(64),
  create_time TIMESTAMP,
  last_visit_time TIMESTAMP,
  daily_challenge VARCHAR(255),
  register_ip VARCHAR(45),
  last_login_ip VARCHAR(45),
  bio VARCHAR(1024),
  is_verified BOOLEAN,
  updated_at TIMESTAMP
);

CREATE TABLE problem (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  create_time TIMESTAMP,
  ac_count INT,
  submit_count INT,
  "desc" CLOB NOT NULL,
  desc_input CLOB NOT NULL,
  desc_output CLOB NOT NULL,
  sample_input CLOB NOT NULL,
  sample_output CLOB NOT NULL,
  hint CLOB,
  daily_challenge VARCHAR(255),
  difficulty VARCHAR(16),
  time_limit_ms INT,
  memory_limit_kb INT,
  source VARCHAR(255),
  is_active BOOLEAN,
  updated_at TIMESTAMP
);

CREATE TABLE discussion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  problem_id BIGINT,
  title VARCHAR(255) NOT NULL,
  create_time TIMESTAMP,
  update_time TIMESTAMP,
  content CLOB,
  view_num INT,
  is_active BOOLEAN
);

CREATE TABLE discussion_comment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discuss_id BIGINT NOT NULL,
  user_id BIGINT,
  parent_comment_id BIGINT,
  reply_to_user_id BIGINT,
  content CLOB NOT NULL,
  create_time TIMESTAMP
);

CREATE TABLE classes_member (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id BIGINT NOT NULL,
  member_type VARCHAR(16) NOT NULL,
  student_id BIGINT,
  teacher_id BIGINT,
  joined_at TIMESTAMP,
  left_at TIMESTAMP
);
CREATE UNIQUE INDEX uk_classes_member_student ON classes_member (student_id, member_type);
ALTER TABLE classes_member ADD CONSTRAINT ck_classes_member_student CHECK (member_type <> 'student' OR student_id IS NOT NULL);

CREATE TABLE homework (
  id BIGINT PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  class_id BIGINT NOT NULL,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  description CLOB,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  is_active BOOLEAN
);

CREATE TABLE homework_problem (
  homework_id BIGINT NOT NULL,
  problem_id BIGINT NOT NULL,
  ac_count INT,
  submit_count INT,
  PRIMARY KEY (homework_id, problem_id)
);

CREATE TABLE judge_status (
  id INT PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  description_en VARCHAR(64) NOT NULL,
  description_zh VARCHAR(64) NOT NULL,
  is_final BOOLEAN,
  is_success BOOLEAN,
  is_compile_error BOOLEAN,
  is_judge_error BOOLEAN,
  sort_order INT
);

CREATE TABLE login_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role VARCHAR(16) NOT NULL,
  user_id BIGINT NOT NULL,
  username VARCHAR(64) NOT NULL,
  ip_address VARCHAR(45),
  location VARCHAR(128),
  user_agent VARCHAR(512),
  device VARCHAR(128),
  login_time TIMESTAMP,
  logout_time TIMESTAMP,
  success BOOLEAN,
  fail_reason VARCHAR(255),
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE problem_testcase (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  problem_id BIGINT NOT NULL,
  input_data CLOB NOT NULL,
  output_data CLOB NOT NULL
);

CREATE TABLE solution (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  problem_id BIGINT NOT NULL,
  title VARCHAR(255),
  content CLOB,
  language VARCHAR(64),
  create_time TIMESTAMP,
  updated_at TIMESTAMP,
  is_active BOOLEAN
);

CREATE TABLE submission_overall_status (
  id INT PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(32) NOT NULL,
  description VARCHAR(255) NOT NULL,
  is_success BOOLEAN
);

CREATE TABLE submission (
  id BIGINT PRIMARY KEY,
  student_id BIGINT NOT NULL,
  problem_id BIGINT NOT NULL,
  homework_id BIGINT,
  language_id INT NOT NULL,
  source_code CLOB NOT NULL,
  overall_status_id INT NOT NULL,
  passed_case_count INT,
  total_case_count INT,
  score INT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE submission_testcase_result (
  id BIGINT PRIMARY KEY,
  submission_id BIGINT NOT NULL,
  testcase_id BIGINT NOT NULL,
  judge0_token VARCHAR(64) NOT NULL,
  status_id INT NOT NULL,
  time_used DECIMAL(10,3),
  memory_used INT,
  stdout CLOB,
  stderr CLOB,
  compile_output CLOB,
  message CLOB,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);
