import type { RouteRecordRaw } from 'vue-router';

export const adminRoutes: RouteRecordRaw[] = [
  {
    path: '/admin',
    component: () => import('@/layouts/AdminLayout.vue'),
    meta: { requiresAuth: true, roles: ['teacher', 'admin'], app: 'admin' },
    children: [
      { path: '', redirect: '/admin/overview' },
      {
        path: 'overview',
        name: 'AdminOverview',
        component: () => import('@/apps/admin/views/AdminDashboard.vue'),
        meta: { title: '仪表盘', requiresAuth: true, roles: ['teacher', 'admin'] },
      },
      {
        path: 'users',
        name: 'AdminUserList',
        component: () => import('@/modules/admin/pages/AdminList.vue'),
        meta: { title: '管理员管理', requiresAuth: true, roles: ['admin'] },
      },
      {
        path: 'users/create',
        name: 'AdminUserCreate',
        component: () => import('@/modules/admin/pages/AdminEdit.vue'),
        meta: { title: '新建管理员', requiresAuth: true, roles: ['admin'] },
      },
      {
        path: 'users/:id/edit',
        name: 'AdminUserEdit',
        component: () => import('@/modules/admin/pages/AdminEdit.vue'),
        meta: { title: '编辑管理员', requiresAuth: true, roles: ['admin'] },
      },
      {
        path: 'teachers',
        name: 'TeacherList',
        component: () => import('@/modules/teacher/pages/TeacherList.vue'),
        meta: { title: '教师管理', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'teachers/create',
        name: 'TeacherCreate',
        component: () => import('@/modules/teacher/pages/TeacherEdit.vue'),
        meta: { title: '新建教师', requiresAuth: true, roles: ['admin'] },
      },
      {
        path: 'teachers/:id/edit',
        name: 'TeacherEdit',
        component: () => import('@/modules/teacher/pages/TeacherEdit.vue'),
        meta: { title: '编辑教师', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'classes',
        name: 'ClassList',
        component: () => import('@/modules/class/pages/ClassList.vue'),
        meta: { title: '班级管理', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'classes/create',
        name: 'ClassCreate',
        component: () => import('@/modules/class/pages/ClassEdit.vue'),
        meta: { title: '新建班级', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'classes/:id/edit',
        name: 'ClassEdit',
        component: () => import('@/modules/class/pages/ClassEdit.vue'),
        meta: { title: '编辑班级', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'classes/:classId/homeworks',
        name: 'HomeworkList',
        component: () => import('@/modules/homework/pages/HomeworkList.vue'),
        meta: { title: '作业管理', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'classes/:classId/homeworks/create',
        name: 'HomeworkCreate',
        component: () => import('@/modules/homework/pages/HomeworkEdit.vue'),
        meta: { title: '新建作业', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'classes/:classId/homeworks/:id/edit',
        name: 'HomeworkEdit',
        component: () => import('@/modules/homework/pages/HomeworkEdit.vue'),
        meta: { title: '编辑作业', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'students',
        name: 'StudentList',
        component: () => import('@/modules/student/pages/StudentList.vue'),
        meta: { title: '学生管理', requiresAuth: true, roles: ['admin'] },
      },
      {
        path: 'students/create',
        name: 'StudentCreate',
        component: () => import('@/modules/student/pages/StudentEdit.vue'),
        meta: { title: '新建学生', requiresAuth: true, roles: ['admin'] },
      },
      {
        path: 'students/:id/edit',
        name: 'StudentEdit',
        component: () => import('@/modules/student/pages/StudentEdit.vue'),
        meta: { title: '编辑学生', requiresAuth: true, roles: ['admin'] },
      },
      {
        path: 'announcements',
        name: 'AnnouncementManageList',
        component: () => import('@/modules/announcement/pages/AnnouncementManageList.vue'),
        meta: { title: '公告管理', requiresAuth: true, roles: ['admin'] },
      },
      {
        path: 'announcements/create',
        name: 'AnnouncementManageCreate',
        component: () => import('@/modules/announcement/pages/AnnouncementManageEdit.vue'),
        meta: { title: '新建公告', requiresAuth: true, roles: ['admin'] },
      },
      {
        path: 'announcements/:id/edit',
        name: 'AnnouncementManageEdit',
        component: () => import('@/modules/announcement/pages/AnnouncementManageEdit.vue'),
        meta: { title: '编辑公告', requiresAuth: true, roles: ['admin'] },
      },
      {
        path: 'login-logs',
        name: 'LoginLogList',
        component: () => import('@/modules/log/pages/LoginLogList.vue'),
        meta: { title: '登录日志', requiresAuth: true, roles: ['admin'] },
      },
      {
        path: 'problems',
        name: 'ProblemList',
        component: () => import('@/modules/problem/pages/ProblemList.vue'),
        meta: { title: '题目管理', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'problems/create',
        name: 'ProblemCreate',
        component: () => import('@/modules/problem/pages/ProblemEdit.vue'),
        meta: { title: '新建题目', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'problems/:id/edit',
        name: 'ProblemEdit',
        component: () => import('@/modules/problem/pages/ProblemEdit.vue'),
        meta: { title: '编辑题目', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'solutions',
        name: 'SolutionList',
        component: () => import('@/modules/solution/pages/SolutionList.vue'),
        meta: { title: '题解管理', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'solutions/create',
        name: 'SolutionCreate',
        component: () => import('@/modules/solution/pages/SolutionEdit.vue'),
        meta: { title: '新建题解', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'solutions/:id/edit',
        name: 'SolutionEdit',
        component: () => import('@/modules/solution/pages/SolutionEdit.vue'),
        meta: { title: '编辑题解', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'discussions',
        name: 'DiscussionList',
        component: () => import('@/modules/discussion/pages/DiscussionList.vue'),
        meta: { title: '讨论管理', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'discussions/create',
        name: 'DiscussionCreate',
        component: () => import('@/modules/discussion/pages/DiscussionEdit.vue'),
        meta: { title: '新建讨论', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
      {
        path: 'discussions/:id/edit',
        name: 'DiscussionEdit',
        component: () => import('@/modules/discussion/pages/DiscussionEdit.vue'),
        meta: { title: '编辑讨论', requiresAuth: true, roles: ['admin', 'teacher'] },
      },
    ],
  },
];
